CELERY_TASK_RESULT_EXPIRES=3600
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
BROKER_URL = 'amqp://'
CELERY_RESULT_BACKEND = 'rpc://'
CELERY_TIMEZONE = 'America/New York'
CELERY_ENABLE_UTC = True
